import type { Preview } from "@storybook/angular";
import { componentWrapperDecorator, moduleMetadata } from "@storybook/angular";
import { setCompodocJson } from "@storybook/addon-docs/angular";
import docJson from "../documentation.json";
import { StorybookThemeSyncComponent } from "./storybook-theme-sync.component";
import recursicaTheme from "./RecursicaTheme";
// Real Recursica design-token CSS custom properties (repo root, generated by
// Forge — see docs/CREATING_AN_ADAPTER.md step 5's "Install Recursica JSON
// and CSS from Forge" note) are wired in via `angular.json`'s
// `storybook`/`build-storybook` architect targets' own `styles` array, not a
// plain import here — see angular.json for why and this repo's
// theme-provider/IMPLEMENTATION_NOTES.md for the full verification writeup.
// A bare `import "../../../recursica_variables_scoped.css"` here fails: this
// file has no loader for a plain top-level CSS import (Storybook's Angular
// webpack config only wires up css-loader/style-loader for CSS reachable
// through Angular's own `styles`-array build pipeline, confirmed by reading
// `@storybook/angular/dist/server/framework-preset-angular-cli.js` and by
// actually trying the plain-import approach first and getting
// "Module parse failed... no loaders are configured" for the .css file).
setCompodocJson(docJson);

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    // Cosmetic Storybook manager-UI (chrome) theming. Ported as-is from the
    // React reference adapter's own `darkMode` parameter — currently inert
    // (nothing reads it; it was written for the `storybook-dark-mode`
    // addon's own sidebar/toolbar styling, which isn't registered here, see
    // `main.ts`), left configured and harmless in case a future addon or
    // Storybook feature consumes it.
    darkMode: {
      current: "light",
      dark: recursicaTheme,
      light: recursicaTheme,
    },
  },
  // Storybook's own native toolbar mechanism (no addon required) — adds the
  // actual light/dark toggle button to Storybook's toolbar. See
  // `storybook-theme-sync.component.ts`'s header comment for why this
  // replaces the (broken, for this Storybook version) `storybook-dark-mode`
  // addon the React reference adapter uses.
  globalTypes: {
    theme: {
      description: "Recursica theme",
      toolbar: {
        title: "Theme",
        icon: "circlehollow",
        items: [
          { value: "light", icon: "sun", title: "Light" },
          { value: "dark", icon: "moon", title: "Dark" },
        ],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: {
    theme: "light",
  },
  // Global decorator, applied to every story in this Storybook instance —
  // wraps each story's rendered content in `StorybookThemeSyncComponent`,
  // which forwards the toolbar's currently-selected theme (read from
  // `storyContext.globals["theme"]` above) to the real `ThemeProviderComponent`
  // (`rec-theme-provider`). See `storybook-theme-sync.component.ts`'s own
  // header comment for the full rationale, including how/why this differs
  // from and improves on the React reference adapter's `ColorSchemeWrapper`.
  decorators: [
    moduleMetadata({ imports: [StorybookThemeSyncComponent] }),
    componentWrapperDecorator(StorybookThemeSyncComponent, (context) => ({
      theme:
        (context.globals["theme"] as "light" | "dark" | undefined) ?? "light",
    })),
  ],
};

export default preview;
