import type { Preview } from "@storybook/angular";
import { setCompodocJson } from "@storybook/addon-docs/angular";
import docJson from "../documentation.json";
// Real Recursica design-token CSS custom properties (repo root, generated by
// Forge — see docs/CREATING_AN_ADAPTER.md step 5's "Install Recursica JSON
// and CSS from Forge" note) are wired in via `angular.json`'s
// `storybook`/`build-storybook` architect targets' own `styles` array, not a
// plain import here — see angular.json for why and this repo's
// theme-provider/IMPLEMENTATION_NOTES.md for the full verification writeup.
// A bare `import "../../../recursica_variables_scoped.css"` here fails: this
// file has no loader for a plain top-level CSS import (Storybook's Angular
// webpack config only wires up css-loader/style-loader for CSS reachable
// through Angular's own `styles`-array build pipeline, confirmed by reading
// `@storybook/angular/dist/server/framework-preset-angular-cli.js` and by
// actually trying the plain-import approach first and getting
// "Module parse failed... no loaders are configured" for the .css file).
setCompodocJson(docJson);

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
